<?php
header('Access-Control-Allow-Origin: *');
/**
 * @return mixed
 */
function ikhwan_core_menu() {
    $items['coremodule'] = array(
        'title' => 'Ikhwan Report Core Module',
        'description' => 'Ikhwan report core module.',
        'page callback' => 'ikhwanreport',
        'access arguments' => array('access ikhwan report core module'),
    );
    $items['masterdata/zone'] = array(
        'title' => 'Data Zone',
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'main-menu',
        'access arguments' => array('admin ikhwan data zone'),
        'page callback' => 'listZone',
        'weight' => 5,
    );
    $items['masterdata/zone/list'] = array(
        'title' => 'List Data Zone',
        'description' => 'List data zone.',
        'page callback' => 'listZone',
        'access arguments' => array('admin ikhwan data zone'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => 0,
    );
    $items['masterdata/zone/add'] = array(
        'title' => 'Form Data Zone',
        'description' => 'Form data zone.',
        'page callback' => 'formZone',
        'access arguments' => array('admin ikhwan data zone'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 1,
    );
    $items['chartsample'] = array(
        'title' => 'Ikhwan Chart Sample',
        'description' => 'Chart example.',
        'page callback' => 'ikhwan_chart_sample',
        'access arguments' => array('access ikhwan report core module'),
        'type' => MENU_CALLBACK,
        'weight' => 0,
    );
    $items['graphkeuangan'] = array(
        'title' => 'Graph Keuangan GISBH',
        'description' => 'Graphic PKH, Dana Yayasan, Mahar MI',
        'page callback' => 'ikhwan_chart_keuangan',
        'access arguments' => array('access ikhwan report core module'),
        'type' => MENU_CALLBACK,
    );
    $items['masterdata/assignment'] = array(
        'title' => 'Data Assignment',
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'main-menu',
        'access arguments' => array('admin ikhwan data assignment'),
        'page callback' => 'listAssigment',
        'weight' => 9,
    );
    $items['masterdata/assignment/list'] = array(
        'title' => 'List Jenis Assignment',
        'description' => 'List jenis assignment.',
        'page callback' => 'listAssigment',
        'access arguments' => array('admin ikhwan jenis assignment'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => 0,
    );
    $items['masterdata/assignment/add'] = array(
        'title' => 'Form Jenis Assignment',
        'description' => 'Form jenis assignment.',
        'page callback' => 'formInputJenisAssigment',
        'access arguments' => array('admin ikhwan jenis assignment'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 1,
    );
    $items['assignmentzone'] = array(
        'title' => 'Assignment Zone',
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'main-menu',
        'access arguments' => array('admin ikhwan data assignment'),
        'page callback' => 'assigmentZone',
        'weight' => 10,
    );
    $items['assignmentdashboard'] = array(
        'title' => t('Assignment Dashboard'),
        'description' => 'GISBH Assignment Dashborad.',
        'page callback' => 'ikhwan_chart_dashboard',
        'access arguments' => array('access ikhwan data assignment'),
        'type' => MENU_CALLBACK,
        'weight' => 0,
    );
    $items['pengeluaranassignment'] = array(
        'title' => 'Pengeluaran Assignment',
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'main-menu',
        'access arguments' => array('admin ikhwan data assignment'),
        'page callback' => 'pengeluaran_assignment',
        'weight' => 11,
    );
    $items['userzone'] = array(
        'title' => 'User Zone/ Premis',
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'main-menu',
        'access arguments' => array('admin ikhwan data zone'),
        'page callback' => 'user_zone',
        'weight' => 12,
    );
    $items['assignmentdashboardtest'] = array(
        'title' => t('Assignment Dashboard'),
        'description' => 'GISBH Assignment Dashborad.',
        'page callback' => 'assignment_total_3d_column_chart',
        'access arguments' => array('access ikhwan data assignment'),
        'type' => MENU_CALLBACK,
        'weight' => 0,
    );
    return $items;
}

/**
 * @return array
 */
function ikhwan_core_permission() {
    return array(
        'access ikhwan report core module' => array(
            'title' => t('access ikhwan report'),
            'description' => t('enable to get access for ikhwan report.'),
        ),
        'access ikhwan report import module' => array(
            'title' => t('access ikhwan report import'),
            'description' => t('enable to get access for ikhwan report import.'),
        ),
        'access ikhwan data zone' => array(
            'title' => t('access ikhwan data zone'),
            'description' => t('enable to get access for ikhwan data zone.'),
        ),
        'admin ikhwan data zone' => array(
            'title' => t('admin ikhwan data zone'),
            'description' => t('enable to manage ikhwan data zone.'),
        ),
        'access ikhwan jenis assignment' => array(
            'title' => t('access ikhwan jenis assignment'),
            'description' => t('enable to get access for ikhwan jenis assignment.'),
        ),
        'admin ikhwan jenis assignment' => array(
            'title' => t('admin ikhwan jenis assignment'),
            'description' => t('enable to manage ikhwan jenis assignment.'),
        ),
        'access ikhwan data assignment' => array(
            'title' => t('access ikhwan data assignment'),
            'description' => t('enable to get access for ikhwan data assignment.'),
        ),
        'admin ikhwan data assignment' => array(
            'title' => t('admin ikhwan data assignment'),
            'description' => t('enable to manage ikhwan data assignment.'),
        ),
        'access ikhwan user zone' => array(
            'title' => t('access ikhwan user zone'),
            'description' => t('enable to get access for ikhwan user zone.'),
        ),
        'admin ikhwan user zone' => array(
            'title' => t('admin ikhwan user zone'),
            'description' => t('enable to manage ikhwan user zone.'),
        ),
    );
}
require_once 'ikhwan_core.api.php.inc';
require_once 'ikhwan_core.chart.inc';
/**
 * @return string
 */
function ikhwanreport(){
    return 'Ikhwan Report Core Module';
}