<?php
header('Access-Control-Allow-Origin: *');
/**
 * @return mixed
 */
function setoran_pengeluaran_menu() {
    $items['setoran'] = array(
        'title' => t('Setoran & Pengeluaran'),
        'type' => MENU_CALLBACK,
        'access arguments' => array('admin data setoran'),
        'page callback' => 'setoran_pengeluaran',
        'weight' => 10,
    );
    $items['inputdetailpengeluaran'] = array(
        'title' => t('Input Detail Pengeluaran'),
        'type' => MENU_CALLBACK,
        'access arguments' => array('admin data setoran'),
        'page callback' => 'input_detail_pengeluaran',
    );
    $items['getpengeluaranajax'] = array(
        'title' => t('Get Data Pengeluaran Ajax'),
        'type' => MENU_CALLBACK,
        'access arguments' => array('access data pengeluaran'),
        'page callback' => 'get_data_pengeluaran_ajax',
    );
    $items['deletepengeluaran'] = array(
        'title' => t('Delete Data Pengeluaran Ajax'),
        'type' => MENU_CALLBACK,
        'access arguments' => array('admin data pengeluaran'),
        'page callback' => 'delete_detail_pengeluaran',
    );
    return $items;
}
/**
 * @return array
 */
function setoran_pengeluaran_permission() {
    return array(
        'access data setoran' => array(
            'title' => t('access data setoran'),
            'description' => t('enable to get access for data setoran.'),
        ),
        'admin data setoran' => array(
            'title' => t('admin data setoran'),
            'description' => t('enable to manage data setoran.'),
        ),
        'access data pengeluaran' => array(
            'title' => t('access data pengeluaran'),
            'description' => t('enable to get access for data pengeluaran.'),
        ),
        'admin data pengeluaran' => array(
            'title' => t('admin data pengeluaran'),
            'description' => t('enable to manage data pengeluaran.'),
        ),
    );
}
require_once 'setoran_pengeluaran.api.php.inc';